account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    #path('login/', views.user_login, name='user_login')
    #path('login/', auth_views.login, name = 'user_login'),
    path('new-login/', auth_views.login, {"template_name":"account/login.html"}, name='user_login'),
    path('logout/', auth_views.logout, {"template_name":"account/logout.html"}, name='user_logout'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.blog_title, name='blog_title'),
    path('<article_id>', views.blog_article, name="blog_detail")
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls','blog'),namespace='blog')),
    path('account/', include(('account.urls',"account"),namespace='account'))
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class BlogArticles(models.Model):
    title = models.CharField('标题', max_length=300)
    author = models.ForeignKey(User,on_delete=models.SET_NULL,related_name="blog_posts",null=True)
    body = models.TextField()
    publish = models.DateTimeField(default= timezone.now)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return  self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    createtime= forms.TimeField()

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2= forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_password2(self):
        cd = self.data
        if cd['password'] != cd['password2']:
            raise forms.forms.ValidationError("Passwords Not Match!")
        return cd['password2']

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, RegistrationForm

# Create your views here.

def user_login(request):
    if request.method == "POST":
        login_form=LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user:
                login(request,user)
                return HttpResponse("Welcome You, You have been authenticated successfully")
            else:
                return HttpResponse("Sorry, something must be wrong")
        else:
            return HttpResponse("Invalid Login")
    if request.method == "GET":
        login_form =LoginForm()
        return render(request, "account/login.html", {"form":login_form})


def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.data['password'])
            new_user.save()
            return HttpResponse("Successfully !")
        else:
            return HttpResponse("You can't register")
    else:
        user_form = RegistrationForm()
        return render(request, "")

blog/views.py
from django.shortcuts import render
from .models import BlogArticles
# Create your views here.

def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request,'blog/title.html',{'blogs':blogs})

def blog_article(request, article_id):
    article = BlogArticles.objects.get(id = article_id)
    pub = article.publish
    return render(request, "blog/content.html", {"article":article, "publish":pub })

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

</head>
<body>
    {% include "header.html" %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/blog/content.html
{% extends "base.html" %}

{% block title %} blog article {% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{article.title}}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-center">
            <span>
                {{ article.author.username }}
            </span>
            <span style="margin-left:20px">
                {{ publish }}
            </span>
        </p>
        <div>
            {{ article.body }}
        </div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>我在学习Python Django</p>
        <img src="http://www.evergrandelife.com.cn/r/cms/www/hengdalifepc/images/banners.jpg" width="200"
    </div>
</div>
{% endblock %}

templates/blog/title.html
{% extends "base.html" %}

{% block title %}blog title {% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1> 我的博客</h1>
</div>

<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
            <li>
                <a href="{{ blog.id }}"> {{blog.title}}| {{blog.publish}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>我在学习Python Django</p>
        <img src="http://www.evergrandelife.com.cn/r/cms/www/hengdalifepc/images/banners.jpg" width="200"
    </div>
</div>
{% endblock %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">Copyright@dyh915.xyz</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.evergrandelife.com.cn">
                <img src="{% static 'images/test.jpg' %}" width="100px" height="20">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-right navbar-nav" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }} </a> </li>
                <li><a href="{% url 'account:user_logout'%}">Logout</a> </li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">Login</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/menu.html
{% extends "base.html" %}

{% block nevigator %}
{% endblock %}

{% block content %}
<div class="list-group">
    <li class="list-item">外部法律法规</li>
    <li class="list-item">公司规章制度</li>
    <li class="list-item">中心内部规范</li>
    <li class="list-item"><a href="https://www.evergrandelife.com.cn">信息安全管理制度</a> </li>
</div>

{% endblock %}